#!/bin/bash

vagrant destroy -f

vagrant up

ansible multi -b -m dnf -a "name=chrony state=present"

ansible multi -b -m service -a "name=chronyd state=started \
enabled=yes"

ansible multi -b -a "chronyc tracking"

ansible app -b -m dnf -a "name=python3-pip state=present"

ansible app -b -m pip -a "executable=pip3 name=django<4 state=present"

ansible app -a "python3 -m django --version"

ansible db -b -m dnf -a "name=mariadb-server state=present"

ansible db -b -m service -a "name=mariadb state=started \
enabled=yes"

ansible db -b -m dnf -a "name=firewalld state=present"

ansible db -b -m service -a "name=firewalld state=started \
enabled=yes"

ansible db -b -m firewalld -a "zone=database state=present permanent=\
yes"

ansible db -b -m firewalld -a "source=192.168.56.0/24 \
zone=database state=enabled permanent=yes"

ansible db -b -m firewalld -a "port=3306/tcp zone=database \
state=enabled permanent=yes"

ansible db -b -m dnf -a "name=python3-PyMySQL state=present"

vagrant ssh db -- "cat <<EOD | sudo mysql 
  USE mysql;
  SET PASSWORD FOR 'root'@'localhost' = PASSWORD('');
  FLUSH PRIVILEGES;
EOD"

ansible db -b -m mysql_user -a "name=django host=% password=12345 \
priv=*.*:ALL state=present"

ansible app -b -m group -a "name=admin state=present"

ansible app -b -m user -a "name=johndoe group=admin createhome=yes"

ansible app -b -m user -a "name=johndoe state=absent remove=yes"

ansible multi -b -B 3600 -P 0 -a "dnf -y update"